# Generated by Django 4.2.4 on 2023-08-31 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=30)),
                ('nomeFiliado', models.CharField(max_length=70)),
                ('especialidade', models.CharField(max_length=30)),
                ('unidade', models.CharField(max_length=20)),
                ('consultor', models.CharField(max_length=30)),
                ('dataDaConsulta', models.CharField(max_length=10)),
                ('dataDeGeracao', models.CharField(max_length=10, null=True)),
                ('useuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
