# Generated by Django 4.2.4 on 2023-09-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_voucher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='unidade',
            field=models.CharField(choices=[('ZL', 'Zona Leste'), ('CN', 'Cidade Nova'), ('C', 'Centro'), ('O', 'Otros')], max_length=20),
        ),
    ]
