# Generated by Django 4.2.4 on 2023-10-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_voucher', '0002_alter_voucher_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='dataDeGeracao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='unidade',
            field=models.CharField(choices=[('ZL', 'Zona Leste'), ('CN', 'Cidade Nova'), ('C', 'Centro'), ('O', 'Otros')], max_length=10),
        ),
    ]
