# Generated by Django 4.2.4 on 2023-10-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_voucher', '0003_alter_voucher_datadegeracao_alter_voucher_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descrição', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
