# Generated by Django 4.2.4 on 2023-10-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_voucher', '0004_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='descrição',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
