# Generated by Django 4.2.4 on 2023-10-20 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_voucher', '0005_alter_especialidade_descrição'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_voucher.especialidade'),
        ),
    ]
