# Generated by Django 4.2.4 on 2023-10-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_voucher', '0007_alter_voucher_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='especialidade',
            field=models.CharField(max_length=30),
        ),
    ]
