# Generated by Django 4.2.4 on 2023-10-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_voucher', '0009_alter_voucher_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
